### PR TITLE
Increase width of side score overlayi

### PR DESCRIPTION
**Pull request by trickeydan**
This fixes the issue where the scores overrun the boxes on the "side overlay"

### CODE REVIEW

**Comment by trickeydan** [comment]
scores

**Comment by PeterJCLaw** [comment]
I guess I was hoping for something which made us a bit more agnostic of the name length, though perhaps that needs too big a change for now?

This seems good as a quick fix though.

**Comment by trickeydan** [comment]
> I guess I was hoping for something which made us a bit more agnostic of the name length, though perhaps that needs too big a change for now?

I agree. However, if we are replacing this codebase, I see little point in sinking lots of time into it. Probably going to be using SFCs for the replacement, so fixing up the slightly messy SCSS we have here doesn't hold a lot of value.

**Review by antoinepetty — APPROVED** [review]
image
Looks good

**Pull request merged**
